[project]
name = "finance-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.1",
    "rich>=13.7.0",
    "streamlit>=1.28.0",
    "plotly>=5.18.0",
    "pandas>=2.1.0",
]
